background-color=#192330
text-color=#cdcecf
border-color=#212f3b
progress-color=over #719cd6

[urgency=low]
border-color=#212f3b

[urgency=normal]
border-color=#212f3b

[urgency=high]
border-color=#c94f6d
text-color=#c94f6d
