-- Theme colors — generated by Matugen (Hyprland Lua config)

local M = {}

M.general = {
    ["col.active_border"] = {
        colors = { "0xee{{colors.primary.default.hex_stripped}}", "0xee{{colors.tertiary.default.hex_stripped}}" },
        angle = 45,
    },
    ["col.inactive_border"] = 0xaa{{colors.surface_container_high.default.hex_stripped}},
}

M.decoration = {
    rounding = 10,
    active_opacity = 1.0,
    inactive_opacity = 0.92,
    shadow = {
        enabled = true,
        range = 12,
        render_power = 3,
        color = 0xee{{colors.surface.default.hex_stripped}},
    },
    blur = {
        enabled = true,
        size = 6,
        passes = 2,
        new_optimizations = true,
    },
}

M.group = {
    ["col.border_active"] = 0xee{{colors.primary.default.hex_stripped}},
    ["col.border_inactive"] = 0xaa{{colors.surface_container_high.default.hex_stripped}},
    ["col.border_locked_active"] = 0xee{{colors.error.default.hex_stripped}},
    ["col.border_locked_inactive"] = 0xaa{{colors.surface_container_high.default.hex_stripped}},
}

return M
