[colors.primary]
background = "#192330"
foreground = "#cdcecf"

[colors.normal]
black   = "#192330"
red     = "#c94f6d"
green   = "#81b29a"
yellow  = "#e3c78a"
blue    = "#719cd6"
magenta = "#ad8ee6"
cyan    = "#70a5b2"
white   = "#cdcecf"

[colors.bright]
black   = "#212f3b"
red     = "#c94f6d"
green   = "#81b29a"
yellow  = "#e3c78a"
blue    = "#719cd6"
magenta = "#ad8ee6"
cyan    = "#70a5b2"
white   = "#cdcecf"
