background #192330
foreground #cdcecf
selection_background #cdcecf
selection_foreground #192330
cursor #cdcecf

color0 #192330
color8 #212f3b
color1 #c94f6d
color9 #c94f6d
color2 #81b29a
color10 #81b29a
color3 #e3c78a
color11 #e3c78a
color4 #719cd6
color12 #719cd6
color5 #ad8ee6
color13 #ad8ee6
color6 #70a5b2
color14 #70a5b2
color7 #cdcecf
color15 #cdcecf
