format = """
[░▒▓](#7dcfff)\
[  ](bg:#7dcfff fg:#1a1b26)\
[](bg:#7aa2f7 fg:#7dcfff)\
$directory\
[](fg:#7aa2f7 bg:#24283b)\
$git_branch\
$git_status\
[](fg:#24283b bg:#16161e)\
$nodejs\
$rust\
$golang\
$php\
[](fg:#16161e bg:#1a1b26)\
$time\
[ ](fg:#1a1b26)\
$character"""

scan_timeout = 200
command_timeout = 5000

[directory]
style = "fg:#c0caf5 bg:#7aa2f7"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = " "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
"Desktop" = " "
"~" = " "
"CPP" = " "
"Cpp" = " "
"C++" = " "
"c++" = " "
"cpp" = " "

[git_branch]
symbol = ""
style = "bg:#24283b"
format = '[[ $symbol $branch ](fg:#7aa2f7 bg:#24283b)]($style)'

[git_status]
style = "bg:#24283b"
format = '[[($all_status$ahead_behind )](fg:#7aa2f7 bg:#24283b)]($style)'

[nodejs]
symbol = ""
style = "bg:#16161e"
format = '[[ $symbol ($version) ](fg:#7aa2f7 bg:#16161e)]($style)'

[rust]
symbol = ""
style = "bg:#16161e"
format = '[[ $symbol ($version) ](fg:#7aa2f7 bg:#16161e)]($style)'

[golang]
symbol = "ﳑ"
style = "bg:#16161e"
format = '[[ $symbol ($version) ](fg:#7aa2f7 bg:#16161e)]($style)'

[php]
symbol = ""
style = "bg:#16161e"
format = '[[ $symbol ($version) ](fg:#7aa2f7 bg:#16161e)]($style)'

[time]
disabled = true
time_format = "%R"
style = "bg:#1a1b26"
format = '[[  $time ](fg:#565f89 bg:#1a1b26)]($style)'
