## Copyright (C) 2020-2026 Aditya Shakya <adi1090x@gmail.com>
##
## Font configuration ---------------------------------------

font=0xProto Nerd Font Propo:size=12
#font=GeistMono Nerd Font Propo Light:size=12
dpi-aware=no
