# Theme colors — sourced from theme engine

general {
    col.active_border = 0xee83a598 0xeeb8bb26 45deg
    col.inactive_border = 0xaa3c3836
}

decoration {
    rounding = 10
    active_opacity = 1.0
    inactive_opacity = 0.92

    shadow {
        enabled = true
        range = 12
        render_power = 3
        color = 0xee282828
    }

    blur {
        enabled = true
        size = 6
        passes = 2
        new_optimizations = true
    }
}

group {
    col.border_active = 0xee83a598
    col.border_inactive = 0xaa3c3836
    col.border_locked_active = 0xeefb4934
    col.border_locked_inactive = 0xaa3c3836
}
