## Copyright (C) 2020-2026 Aditya Shakya <adi1090x@gmail.com>
##
## Font configuration ---------------------------------------

#-fn-start
font_family          0xProto Nerd Font Propo
bold_font            0xProto Nerd Font Propo
italic_font          0xProto Nerd Font Propo
bold_italic_font     0xProto Nerd Font Propo
#-fn-end

font_size 12
