background-color=#282a36
text-color=#f8f8f2
border-color=#343746
progress-color=over #bd93f9

[urgency=low]
border-color=#343746

[urgency=normal]
border-color=#343746

[urgency=high]
border-color=#ff5555
text-color=#ff5555
