background-color=#2d353b
text-color=#d3c6aa
border-color=#3d484d
progress-color=over #7fbbb3

[urgency=low]
border-color=#3d484d

[urgency=normal]
border-color=#3d484d

[urgency=high]
border-color=#e67e80
text-color=#e67e80
