background-color=#1e1e1e
text-color=#d4d4d4
border-color=#2d2d2d
progress-color=over #9e9e9e

[urgency=low]
border-color=#2d2d2d

[urgency=normal]
border-color=#2d2d2d

[urgency=high]
border-color=#c75050
text-color=#c75050
