background #1f1f28
foreground #dcd7ba
selection_background #dcd7ba
selection_foreground #1f1f28
cursor #dcd7ba

color0 #1f1f28
color8 #2a2a37
color1 #c34043
color9 #c34043
color2 #98bb6c
color10 #98bb6c
color3 #c0a36e
color11 #c0a36e
color4 #7e9cd8
color12 #7e9cd8
color5 #957fb8
color13 #957fb8
color6 #7aa89f
color14 #7aa89f
color7 #dcd7ba
color15 #dcd7ba
