# Window rules — formato conf

# Firefox
windowrule = match:class firefox, workspace 2
windowrule = match:class firefox, match:title (Picture-in-Picture), float on
windowrule = match:class firefox, match:title (Picture-in-Picture), move 100%-w-40 100%-w-40

# brave-origin-nightly
windowrule = match:class brave-origin-nightly, workspace 8
windowrule = match:class brave-origin-nightly, match:title (Picture-in-Picture), float on
windowrule = match:class brave-origin-nightly, match:title (Picture-in-Picture), move 100%-w-40 100%-w-40

# Blueman / gmetronome (workspace 9)
windowrule = match:class Blueman-manager|blueman-manager, workspace 9 silent, float on, size 638 506, move 18 242
windowrule = match:class gmetronome, workspace 9 silent, float on, size 487 391, move 1327 305

# Floating dialogs
windowrule = match:class foot-float|alacritty-float|kitty-float, float on
windowrule = match:class yad|Yad|nm-connection-editor|xfce-polkit|kvantummanager|qt5ct|qt6ct|feh|viewnior|gimp|MPlayer|VirtualBox Manager|qemu|Qemu-system-x86_64|io.calamares.calamares, float on
windowrule = match:title File Operation Progress, float on
windowrule = match:title Confirm to replace files, float on

windowrule = match:class org.pulseaudio.pavucontrol, float on, size 800 600
windowrule = match:class thunar, match:title Rename .*, float on
windowrule = match:class Yad|yad, float on, size 60% 64%
windowrule = match:class io.calamares.calamares, float on, center on
windowrule = match:title ^(Archcraft Installer)(.*)$, float on
windowrule = match:class viewnior, size 800 600, center on
windowrule = match:class Alacritty|alacritty|alacritty-float, size 785 450

windowrule = match:class foot-full|alacritty-full|kitty-full, animation slide down
windowrule = match:class wlogout, animation slide up

# Media players (workspace 8)
windowrule = match:class mpv|vlc|org.videolan.vlc|celluloid|io.github.celluloid_player.Celluloid|io.github.diegopvlk.Cine, workspace 8 silent

layerrule = match:namespace rofi, animation slide
layerrule = match:namespace notifications, animation slide
