background-color=#282c34
text-color=#abb2bf
border-color=#2c323c
progress-color=over #61afef

[urgency=low]
border-color=#2c323c

[urgency=normal]
border-color=#2c323c

[urgency=high]
border-color=#e06c75
text-color=#e06c75
